import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {clone} from 'three/addons/utils/SkeletonUtils.js';
import {V,rand,range,clamp} from './config.js';
const skins=[0xe5bca0,0xc28b66,0x9b674b,0x684536,0xf0d0b5,0xb27958,0xd4a87e];
const hairColors=[0x27211c,0x503726,0xb49355,0x9f5939,0x5a4a38,0x9a9690,0x292327];
const colors=[0x284f65,0xb05d48,0x69916e,0xe6bc5f,0x987ab3,0xf19b89,0x457e86,0x222e34];
function garmentTexture(color,pattern){const c=document.createElement('canvas');c.width=c.height=128;const g=c.getContext('2d');g.fillStyle='#'+color.toString(16).padStart(6,'0');g.fillRect(0,0,128,128);g.globalAlpha=.22;for(let y=0;y<128;y+=2){g.fillStyle='#fff';g.fillRect(0,y,128,.35)}g.globalAlpha=.6;if(pattern==='stripe'){g.fillStyle='#eee8da';for(let x=0;x<128;x+=24)g.fillRect(x,0,7,128)}else if(pattern==='dot'){g.fillStyle='#efe7d6';for(let y=8;y<128;y+=23)for(let x=8;x<128;x+=23){g.beginPath();g.arc(x+(y%2)*5,y,3,0,7);g.fill()}}else if(pattern==='botanical'){g.strokeStyle='#d0e0c1';g.lineWidth=2;for(let y=0;y<128;y+=32)for(let x=0;x<128;x+=32){g.beginPath();g.moveTo(x,y+22);g.quadraticCurveTo(x+20,y+6,x+8,y);g.stroke();for(let j=0;j<4;j++){g.beginPath();g.ellipse(x+7+j*2,y+4+j*4,6,2,-.6,0,7);g.fillStyle='#becdab';g.fill()}}}let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(4,4);return t}
function subset(source,predicate,offset=0){const g=source.clone();const p=g.attributes.position,n=g.attributes.normal,ids=[];const idx=g.index;for(let i=0;i<idx.count;i+=3){let a=idx.getX(i),b=idx.getX(i+1),c=idx.getX(i+2);const x=(p.getX(a)+p.getX(b)+p.getX(c))/3,y=(p.getY(a)+p.getY(b)+p.getY(c))/3,z=(p.getZ(a)+p.getZ(b)+p.getZ(c))/3;if(predicate(x,y,z))ids.push(a,b,c)}for(let i=0;i<p.count;i++){p.setXYZ(i,p.getX(i)+n.getX(i)*offset,p.getY(i)+n.getY(i)*offset,p.getZ(i)+n.getZ(i)*offset)}g.setIndex(ids);g.computeBoundingSphere();return g}
// Clip fabric shells at exact hems, interpolating both geometry and bone weights.
function fittedGarment(source,style){
 const regions=[{low:.56,high:1.015,width:1}];if(style==='rash')regions.push({low:1.012,high:1.40,width:.40});if(style==='onepiece')regions.push({low:1.012,high:1.37,width:.245});if(style==='sport')regions.push({low:1.17,high:1.35,width:.245});
 const attrs=source.attributes,index=source.index,out={position:[],normal:[],uv:[],skinIndex:[],skinWeight:[]};
 const vertex=id=>{const w={};for(let k=0;k<4;k++){let b=attrs.skinIndex[['getX','getY','getZ','getW'][k]](id),v=attrs.skinWeight[['getX','getY','getZ','getW'][k]](id);w[b]=(w[b]||0)+v}return{p:[attrs.position.getX(id),attrs.position.getY(id),attrs.position.getZ(id)],n:[attrs.normal.getX(id),attrs.normal.getY(id),attrs.normal.getZ(id)],uv:[attrs.uv.getX(id),attrs.uv.getY(id)],w}};
 const mix=(a,b,t)=>{const v={p:a.p.map((x,i)=>x+(b.p[i]-x)*t),n:a.n.map((x,i)=>x+(b.n[i]-x)*t),uv:a.uv.map((x,i)=>x+(b.uv[i]-x)*t),w:{}};for(const k of new Set([...Object.keys(a.w),...Object.keys(b.w)]))v.w[k]=(a.w[k]||0)*(1-t)+(b.w[k]||0)*t;return v};
 const clip=(poly,axis,limit,positive)=>{const next=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=(a.p[axis]-limit)*positive,db=(b.p[axis]-limit)*positive;if(da>=0)next.push(a);if((da>=0)!==(db>=0))next.push(mix(a,b,da/(da-db)))}return next};
 const emit=v=>{const normal=new THREE.Vector3(...v.n).normalize();out.position.push(v.p[0]+normal.x*.027,v.p[1]+normal.y*.027,v.p[2]+normal.z*.027);out.normal.push(...normal.toArray());out.uv.push(...v.uv);let weights=Object.entries(v.w).sort((a,b)=>b[1]-a[1]).slice(0,4);while(weights.length<4)weights.push([0,0]);const total=weights.reduce((s,x)=>s+x[1],0)||1;out.skinIndex.push(...weights.map(x=>Number(x[0])));out.skinWeight.push(...weights.map(x=>x[1]/total))};
 for(const r of regions)for(let j=0;j<index.count;j+=3){let poly=[vertex(index.getX(j)),vertex(index.getX(j+1)),vertex(index.getX(j+2))];poly=clip(poly,1,r.low,1);poly=clip(poly,1,r.high,-1);poly=clip(poly,0,-r.width,1);poly=clip(poly,0,r.width,-1);for(let k=1;k<poly.length-1;k++)[poly[0],poly[k],poly[k+1]].forEach(emit)}
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(out.position,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(out.normal,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(out.uv,2));g.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(out.skinIndex,4));g.setAttribute('skinWeight',new THREE.Float32BufferAttribute(out.skinWeight,4));g.computeBoundingSphere();return g;
}
export class CharacterFactory{
 async load(){const gltf=await new GLTFLoader().loadAsync(new URL('../assets/characters/visitor.glb',import.meta.url).href);this.skinTexture=await new THREE.TextureLoader().loadAsync(new URL('../assets/characters/skin.webp',import.meta.url).href);this.skinTexture.colorSpace=THREE.SRGBColorSpace;this.base=gltf.scene;let mesh;this.base.traverse(o=>{if(o.isSkinnedMesh)mesh=o});this.source=mesh;this.templates=[];for(let i=0;i<12;i++)this.templates.push(this.makeTemplate(i));return this}
 makeTemplate(i){const root=clone(this.base);let body;root.traverse(o=>{if(o.isSkinnedMesh)body=o});const female=i%3!==0,child=i>=10,old=i===8||i===9,build=i%4;const skinMat=new THREE.MeshStandardMaterial({color:skins[i%skins.length],roughness:.69,metalness:0,map:this.skinTexture});skinMat.onBeforeCompile=shader=>{shader.vertexShader='varying float skinHeight;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nskinHeight=position.y;');shader.fragmentShader='varying float skinHeight;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\ndiffuseColor.rgb=mix(diffuse,diffuseColor.rgb,smoothstep(1.41,1.49,skinHeight));')};body.geometry=body.geometry.clone();let pos=body.geometry.attributes.position;for(let k=0;k<pos.count;k++){let x=pos.getX(k),y=pos.getY(k),z=pos.getZ(k);const trunk=Math.exp(-(((y-1.12)/.23)**2));const width=build===1?1.12:build===2?.94:1;if(y<1.4&&y>.85){x*=width;if(build===1)z+=trunk*.035;if(female){x*=y>1.21?.95:y<1.05?1.11:.93;if(z>.035&&y>1.12&&y<1.37){z+=.052*Math.exp(-(((y-1.25)/.09)**2))*Math.exp(-(((Math.abs(x)-.095)/.07)**2))}}}if(y>.66&&y<.97&&Math.abs(x)<.095)z=Math.min(z,.105);pos.setXYZ(k,x,y,z)}body.geometry.computeVertexNormals();
 const style=child?'rash':female?(i%3===1?'onepiece':'sport'):(i%2?'rash':'trunks');const covers=(x,y,z)=>{if(y>.56&&y<1.02)return true;if(style==='rash'&&y>=.98&&y<1.42&&Math.abs(x)<.35)return true;if(style==='onepiece'&&y>=.94&&y<1.38&&Math.abs(x)<.27)return true;if(style==='sport'&&y>=1.15&&y<1.36&&Math.abs(x)<.26)return true;return false};const clothGeometry=fittedGarment(body.geometry,style);const clothMaterial=new THREE.MeshStandardMaterial({map:garmentTexture(colors[i%colors.length],['solid','botanical','stripe','dot'][i%4]),roughness:.89,side:THREE.DoubleSide});const cloth=new THREE.SkinnedMesh(clothGeometry,clothMaterial);cloth.bind(body.skeleton,body.bindMatrix);cloth.name='fitted-swimwear';body.parent.add(cloth);body.geometry=subset(body.geometry,(x,y,z)=>!((y>.585&&y<.99)||(style==='rash'&&y>1.035&&y<1.375&&Math.abs(x)<.375)||(style==='onepiece'&&y>1.035&&y<1.345&&Math.abs(x)<.22)||(style==='sport'&&y>1.195&&y<1.325&&Math.abs(x)<.22)));body.material=skinMat;body.castShadow=true;cloth.castShadow=true;
 const hairGeo=subset(this.source.geometry,(x,y,z)=>y>1.58||(y>1.51&&z<-.012),.015);const hair=new THREE.SkinnedMesh(hairGeo,new THREE.MeshStandardMaterial({color:old?0xa6a398:hairColors[i%hairColors.length],roughness:.92}));hair.bind(body.skeleton,body.bindMatrix);body.parent.add(hair);hair.castShadow=true;
 const bones={};root.traverse(o=>{if(o.isBone)bones[o.name]=o});root.updateMatrixWorld(true);const head=bones.head;if(child&&head)head.scale.multiplyScalar(1.15);if(head){const wp=head.getWorldPosition(V());head.updateWorldMatrix(true,false);const inv=head.matrixWorld.clone().invert();function attachAt(object,world){object.position.copy(world.applyMatrix4(inv));head.add(object)}
 // True modeled eyes in the anatomical face, plus brows. No billboard faces.
 for(let s of [-1,1]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.0155,12,8),new THREE.MeshStandardMaterial({color:0xe8ded0,roughness:.4}));attachAt(eye,V(s*.031,1.555,.112));const iris=new THREE.Mesh(new THREE.SphereGeometry(.007,10,7),new THREE.MeshStandardMaterial({color:i%3?0x3b3930:0x657f7a,roughness:.5}));attachAt(iris,V(s*.031,1.555,.125));const brow=new THREE.Mesh(new THREE.BoxGeometry(.044,.007,.005),hair.material);attachAt(brow,V(s*.031,1.582,.107))}
 if(female&&!child){for(let j=0;j<7;j++){const a=j/7*6.28;const curve=new THREE.CatmullRomCurve3([V(Math.cos(a)*.065,1.65,Math.sin(a)*.065+.018),V(Math.cos(a)*.105,1.50,Math.sin(a)*.065-.01),V(Math.cos(a)*.09,1.34,-.045)]);const g=new THREE.TubeGeometry(curve,10,.016,5,false);g.applyMatrix4(inv);const strand=new THREE.Mesh(g,hair.material);head.add(strand)}}
 if(i===7||child){const cap=new THREE.Mesh(new THREE.SphereGeometry(.102,18,12,0,Math.PI*2,0,Math.PI/2),new THREE.MeshStandardMaterial({color:colors[(i+3)%8],roughness:.8}));cap.scale.set(1,1.12,1.15);attachAt(cap,V(0,1.585,.013))}
 }
 // Rest positions are retained; runtime motion rotates the actual skeleton around world-aligned axes.
 root.userData={female,child,old,bones,rest:Object.fromEntries(Object.entries(bones).map(([k,b])=>[k,b.quaternion.clone()]))};const wrapped=new THREE.Group();wrapped.add(root);wrapped.userData=root.userData;wrapped.userData.rig=root;wrapped.scale.setScalar(child?(i===10?.64:.89):range(.94,1.10));return wrapped
 }
 create(index=0){const template=this.templates[index%this.templates.length];const saved=[];template.traverse(o=>{saved.push([o,o.userData]);o.userData={}});const obj=clone(template);saved.forEach(([o,data])=>o.userData=data);const rig=obj.children[0],bones={},rest={};rig.traverse(o=>{if(o.isBone){bones[o.name]=o;rest[o.name]=o.quaternion.clone()}});obj.userData={...template.userData,bones,rest,rig};return obj}
 animate(obj,state,time,speed=1){const{bones,rest}=obj.userData;for(const[k,b]of Object.entries(bones))b.quaternion.copy(rest[k]);const rotate=(name,axis,angle)=>{const bone=bones[name];if(!bone)return;bone.parent.updateWorldMatrix(true,false);const parentQ=bone.parent.getWorldQuaternion(new THREE.Quaternion()).invert();const localAxis=axis.clone().applyQuaternion(obj.getWorldQuaternion(new THREE.Quaternion())).applyQuaternion(parentQ);bone.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(localAxis,angle))};const phase=time*(state==='walk'||state==='climb'?5:2.2),s=Math.sin(phase); // arms lowered from A-pose
 rotate('upperarm_l',V(0,0,1),-.85);rotate('upperarm_r',V(0,0,1),.85);
 if(state==='walk'||state==='climb'){rotate('thigh_l',V(1,0,0),s*.34);rotate('thigh_r',V(1,0,0),-s*.34);rotate('calf_l',V(1,0,0),Math.max(0,-s)*.42);rotate('calf_r',V(1,0,0),Math.max(0,s)*.42);rotate('upperarm_l',V(1,0,0),-s*.24);rotate('upperarm_r',V(1,0,0),s*.24)}else if(state==='swim'||state==='float'){rotate('upperarm_l',V(0,0,1),.75+Math.sin(phase)*.23);rotate('upperarm_r',V(0,0,1),-.75-Math.sin(phase)*.23);rotate('lowerarm_l',V(1,0,0),-.45);rotate('lowerarm_r',V(1,0,0),-.45);rotate('thigh_l',V(1,0,0),s*.15);rotate('thigh_r',V(1,0,0),-s*.15)}else if(state==='sit'||state==='ride'){rotate('thigh_l',V(1,0,0),-1.05);rotate('thigh_r',V(1,0,0),-1.05);rotate('calf_l',V(1,0,0),1.05);rotate('calf_r',V(1,0,0),1.05);rotate('upperarm_l',V(1,0,0),-.55);rotate('upperarm_r',V(1,0,0),-.55)}else if(state==='talk'){rotate('lowerarm_l',V(1,0,0),-.7-.18*s);rotate('head',V(0,1,0),Math.sin(time*.6)*.1)}else{rotate('head',V(0,1,0),Math.sin(time*.55)*.10);rotate('spine_03',V(0,0,1),Math.sin(time*.8)*.015)}obj.updateMatrixWorld(true)
 }
}
