import * as THREE from 'three';
import {Rendering} from './rendering.js';
import {initMaterials} from './materials.js';
import {Environment} from './environment.js';
import {WaterSystem} from './water.js';
import {SlideSystem} from './slides.js';
import {CharacterFactory} from './characters.js';
import {Visitors} from './visitors.js';
import {Player} from './player.js';
import {Input} from './input.js';
import {ParkAudio} from './audio.js';
import {UI,$,toast} from './ui.js';
const params=new URLSearchParams(location.search),mobile=matchMedia('(pointer: coarse)').matches||innerWidth<700||params.has('mobile');
let app=null,ready=false,fatal=false;function fail(error){fatal=true;console.error(error);document.documentElement.dataset.status='error';$('#loader').style.opacity=1;$('#loader').hidden=false;$('#loader h2').textContent='The cove couldn’t open';$('#loading-text').textContent=(error?.message||String(error))+' · Reload, or choose a browser with WebGL2 enabled.';$('#retry').hidden=false}
window.addEventListener('error',e=>fail(e.error||e.message));window.addEventListener('unhandledrejection',e=>fail(e.reason));$('#scene').addEventListener('webglcontextlost',e=>{e.preventDefault();fail('The graphics context was lost. Other open tabs may be using graphics memory.')});$('#scene').addEventListener('webglcontextrestored',()=>location.reload());
async function start(){const rendering=new Rendering($('#scene'),mobile);await initMaterials();$('#loading-text').textContent='Laying the beach and growing the palms…';const environment=new Environment(rendering.scene);const slides=new SlideSystem(rendering.scene,environment);const water=new WaterSystem(rendering.scene,mobile);$('#loading-text').textContent='Getting the visitors ready…';const factory=await new CharacterFactory().load();const visitors=new Visitors(factory,rendering.scene,environment,slides,water,mobile);const player=new Player(environment,slides,water,rendering.scene),input=new Input($('#scene')),audio=new ParkAudio();player.avatar=factory.create(3);rendering.scene.add(player.avatar);app={rendering,environment,slides,water,factory,visitors,player,input,audio,mobile};const ui=new UI(app);app.ui=ui;
 const shaderErrors=[];rendering.renderer.debug.onShaderError=(gl,program,vs,fs)=>{const message=[gl.getProgramInfoLog(program),gl.getShaderInfoLog(vs),gl.getShaderInfoLog(fs)].join('\n');shaderErrors.push(message);fail('Waterpark shader compilation failed: '+message.slice(0,280))};
 let last=performance.now(),t=0,fps=60,frames=0,renderedFrames=0,sample=0,slowSamples=0;function tick(now){if(fatal)return;requestAnimationFrame(tick);if(document.hidden||params.has('qa')&&app.qaPaused){last=now;return}const wallDt=(now-last)/1000,dt=Math.min(.035,wallDt);last=now;t+=dt;frames++;sample+=wallDt;if(sample>=1){fps=frames/sample;frames=0;sample=0;if(mobile&&$('#quality').value==='auto'){slowSamples=fps<26?slowSamples+1:0;if(slowSamples>=4){const dpr=Math.max(.72,rendering.renderer.getPixelRatio()-.12);rendering.renderer.setPixelRatio(dpr);rendering.resize();water.mobile=true;slowSamples=0}}}if(ui.active&&!ui.overview&&$('#guide').hidden)player.update(dt,t,input);slides.update(t);water.update(t,dt);visitors.update(dt,t);const underwater=player.cameraPose(rendering.camera,dt,t,!ui.active||ui.overview);$('#underwater').style.opacity=underwater?1:0;rendering.scene.fog.density=underwater?.07:.004;rendering.scene.fog.color.set(underwater?0x297a7d:rendering.golden?0xd4be9f:0xb1d5cc);player.avatar.visible=ui.active&&player.third&&!ui.overview;player.avatar.position.copy(player.position);if(player.ride)player.avatar.position.y-=.55;player.avatar.rotation.y=player.ride?Math.atan2(player.ride.frame.tangent.x,player.ride.frame.tangent.z):player.yaw+Math.PI;factory.animate(player.avatar,player.ride?'ride':player.mode==='swim'?'swim':player.speed>.1?'walk':'idle',t);ui.update(t,fps);audio.update(player.speed,underwater);rendering.renderer.render(rendering.scene,rendering.camera);renderedFrames++;if(!ready&&renderedFrames>=3&&shaderErrors.length===0){ready=true;document.documentElement.dataset.status='ready';$('#loader').style.opacity=0;setTimeout(()=>$('#loader').hidden=true,650)}if(params.has('qa'))$('#diagnostics').dataset.metrics=JSON.stringify({fps,calls:rendering.renderer.info.render.calls,triangles:rendering.renderer.info.render.triangles,position:player.position.toArray(),mode:player.mode,ride:player.ride?.phase,shaderErrors})}
 requestAnimationFrame(tick);if(params.has('qa')){window.tidal=app;const{attachQA}=await import('./qa.js');attachQA(app)}
}
start().catch(fail);
