import * as THREE from 'three';
import {V,poolAt,poolBottom,waveHeight,clamp} from './config.js';
import {Ride,makeTube} from './slides.js';
export class Player{
 constructor(environment,slides,water,scene){this.environment=environment;this.slides=slides;this.water=water;this.position=V(8,0,40);this.yaw=0;this.pitch=0;this.mode='walk';this.third=false;this.floating=false;this.ride=null;this.speed=0;this.vertical=0;this.scene=scene;this.tube=makeTube();this.tube.visible=false;scene.add(this.tube);this.avatar=null;this.completed=new Set((()=>{try{const a=JSON.parse(localStorage.getItem('tidal-rides')||'[]');return Array.isArray(a)?a:[]}catch{return[]}})());this.splashFlash=0;this.transition=0;this.flightVerified=false}
 start(r){this.ride=new Ride(r);this.mode='ride';this.floating=false;this.position.copy(r.launch);this.tube.visible=!!r.tube;this.transition=0}
 update(dt,t,input){if(this.mode==='ride'){const ride=this.ride;const was=ride.phase;ride.update(dt);this.position.copy(ride.p);if(ride.phase==='flight')this.flightVerified=true;if(was!==ride.phase&&ride.phase==='splash'){this.water.splash(this.position.x,this.position.z,ride.config.jump?2.5:1.8);this.splashFlash=1;}if(ride.phase==='done'){this.completed.add(ride.config.id);try{localStorage.setItem('tidal-rides',JSON.stringify([...this.completed]))}catch{};this.mode='swim';this.position.y=-.6;this.yaw=Math.atan2(-ride.frame.tangent.x,-ride.frame.tangent.z);this.pitch=0;this.tube.visible=!!ride.config.tube;this.transition=2;this.ride=null}if(this.tube.visible){this.tube.position.copy(this.position).add(V(0,.08,0));this.tube.rotation.set(0,t*.9,0);this.tube.rotateZ(ride.frame.bank)}this.speed=ride.speed;return}
 this.yaw-=input.look.x;this.pitch=clamp(this.pitch-input.look.y,-1.1,1.05);input.look.x=input.look.y=0;const a=input.axes();let pool=poolAt(this.position.x,this.position.z),floor=this.environment.floor(this.position.x,this.position.z,this.position.y);const depth=pool?-poolBottom(pool,this.position.x,this.position.z):0;this.mode=depth>1.18?'swim':depth>.15?'wade':'walk';const maxSpeed=this.mode==='swim'?2.8:this.mode==='wade'?3.4:input.keys.ShiftLeft?6:4.2;const moving=Math.hypot(a.x,a.y);this.speed=moving*maxSpeed;const dx=(Math.cos(this.yaw)*a.x-Math.sin(this.yaw)*a.y)*maxSpeed*dt,dz=(-Math.sin(this.yaw)*a.x-Math.cos(this.yaw)*a.y)*maxSpeed*dt;const nx=this.position.x+dx,nz=this.position.z+dz;if(!this.environment.blocked(nx,this.position.z,this.position.y)){const h=this.environment.floor(nx,this.position.z,this.position.y);if(h-this.position.y<.45)this.position.x=nx}if(!this.environment.blocked(this.position.x,nz,this.position.y)){const h=this.environment.floor(this.position.x,nz,this.position.y);if(h-this.position.y<.45)this.position.z=nz}pool=poolAt(this.position.x,this.position.z);floor=this.environment.floor(this.position.x,this.position.z,this.position.y);
 if(this.mode==='swim'){const dive=input.keys.Space||input.dive;const target=waveHeight(this.position.x,this.position.z,t,this.water.on)-(dive?1.75:this.floating?.78:.65);this.position.y=THREE.MathUtils.damp(this.position.y,Math.max(floor+.1,target),6,dt);this.vertical=0;if(pool?.id==='wave'&&this.water.on){this.position.z+=Math.cos(this.position.z*.48+t*1.65)*.08*dt;this.position.x+=Math.sin(t*.8)*.02*dt}if(moving>.1&&Math.random()<dt*1.4)this.water.splash(this.position.x,this.position.z,.45)}else{if(floor>=this.position.y-.45){this.position.y=floor;this.vertical=0}else{this.vertical-=9.81*dt;this.position.y=Math.max(floor,this.position.y+this.vertical*dt)}}
 if(this.transition>0){this.transition-=dt;if(this.tube.visible){this.tube.position.copy(this.position).add(V(0,.65,0));this.tube.rotation.y+=dt*.2;if(!pool||this.transition<=0)this.tube.visible=false}}this.splashFlash=Math.max(0,this.splashFlash-dt*1.8);
 }
 cameraPose(camera,dt,t,overview=false){let eye,target,up=V(0,1,0),fov=66;if(overview){const a=t*.018+.48;eye=V(70*Math.sin(a),51,70*Math.cos(a));target=V(-5,4,-5)}else if(this.ride){const ride=this.ride,f=ride.frame;if(ride.phase==='flight'||ride.phase==='splash'){const forward=ride.velocity.clone().normalize();eye=this.position.clone().add(V(0,.55,0));target=eye.clone().add(forward);if(ride.phase==='splash')target=eye.clone().add(V(0,.1,-1))}else{eye=this.position.clone().addScaledVector(f.up,.6);target=eye.clone().addScaledVector(f.tangent,3).addScaledVector(f.up,-.07);up.lerp(f.up,.65);fov=68+ride.speed*.63;if(ride.phase==='countdown')target=eye.clone().add(V(1,-.15,0));if(ride.config.tube&&this.third){eye=this.position.clone().addScaledVector(f.tangent,-2.8).addScaledVector(f.up,1.4);target=this.position.clone().addScaledVector(f.tangent,3)}}}else{const forward=V(-Math.sin(this.yaw)*Math.cos(this.pitch),Math.sin(this.pitch),-Math.cos(this.yaw)*Math.cos(this.pitch));const head=this.position.clone().add(V(0,this.mode==='swim'?1.02:1.64,0));eye=head.clone();target=head.clone().add(forward);if(this.third){eye=head.clone().addScaledVector(forward,-3.4).add(V(0,.7,0));target=head.clone().addScaledVector(forward,1.8);const ray=new THREE.Raycaster(head,eye.clone().sub(head).normalize(),.1,head.distanceTo(eye));const hits=ray.intersectObjects(this.slides.rides.map(r=>r.mesh),false);if(hits[0])eye.copy(head).addScaledVector(ray.ray.direction,Math.max(.35,hits[0].distance-.2));eye.y=Math.max(eye.y,this.environment.floor(eye.x,eye.z,eye.y)+.25)}}
 camera.position.copy(eye);camera.up.copy(up);camera.lookAt(target);camera.fov=THREE.MathUtils.damp(camera.fov,fov,5,dt);camera.updateProjectionMatrix();return camera.position.y<waveHeight(camera.position.x,camera.position.z,t,this.water.on)&&!!poolAt(camera.position.x,camera.position.z)
 }
}
