import * as THREE from 'three';
import {Sky} from 'three/addons/objects/Sky.js';
import {V} from './config.js';
export class Rendering{
 constructor(canvas,mobile){this.mobile=mobile;this.renderer=new THREE.WebGLRenderer({canvas,antialias:!mobile,alpha:false,powerPreference:'high-performance'});const r=this.renderer;r.setPixelRatio(Math.min(devicePixelRatio,mobile?1.15:1.6));r.setSize(innerWidth,innerHeight,false);r.outputColorSpace=THREE.SRGBColorSpace;r.toneMapping=THREE.ACESFilmicToneMapping;r.toneMappingExposure=.79;r.shadowMap.enabled=true;r.shadowMap.type=THREE.PCFSoftShadowMap;this.scene=new THREE.Scene();this.scene.fog=new THREE.FogExp2(0xb1d5cc,.004);this.camera=new THREE.PerspectiveCamera(66,innerWidth/innerHeight,.065,650);this.sky=new Sky();this.sky.scale.setScalar(450);this.scene.add(this.sky);const u=this.sky.material.uniforms;u.turbidity.value=3;u.rayleigh.value=1.65;u.mieCoefficient.value=.003;u.mieDirectionalG.value=.8;this.sun=new THREE.DirectionalLight(0xfff2d2,2.25);this.sun.position.set(-44,72,36);this.sun.castShadow=true;this.sun.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);Object.assign(this.sun.shadow.camera,{left:-75,right:75,top:75,bottom:-75,near:1,far:220});this.sun.shadow.bias=-.00045;this.sun.shadow.normalBias=.06;this.scene.add(this.sun);this.hemi=new THREE.HemisphereLight(0xc4e9ee,0xa5a37a,.7);this.scene.add(this.hemi);this.sunDirection=V(-.44,.72,.36).normalize();u.sunPosition.value.copy(this.sunDirection);const envScene=new THREE.Scene();const envSky=this.sky.clone();envScene.add(envSky);this.pmrem=new THREE.PMREMGenerator(r);this.environment=this.pmrem.fromScene(envScene,.025,.1,600);this.scene.environment=this.environment.texture;this.scene.environmentIntensity=.32;this.golden=false;window.addEventListener('resize',()=>this.resize())}
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight,false)}
 quality(value){const mobile=value==='mobile'||value==='auto'&&this.mobile;this.renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1:1.75));this.renderer.shadowMap.enabled=true;this.sun.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);if(this.sun.shadow.map){this.sun.shadow.map.dispose();this.sun.shadow.map=null}this.resize()}
 sunset(){this.golden=!this.golden;this.sun.color.set(this.golden?0xffbe7b:0xfff2d2);this.sun.intensity=this.golden?2.1:2.25;this.sun.position.set(-65,this.golden?29:72,36);this.sky.material.uniforms.sunPosition.value.copy(this.sun.position).normalize();this.sky.material.uniforms.turbidity.value=this.golden?6:3;this.hemi.intensity=this.golden?.6:.7;this.scene.fog.color.set(this.golden?0xd4be9f:0xb1d5cc)}
}
