import * as THREE from 'three';
import {V,rideDefinitions,clamp} from './config.js';
import {mats,sign} from './materials.js';
export function slideFrame(curve,t){const p=curve.getPointAt(clamp(t,0,1)),tangent=curve.getTangentAt(clamp(t,0,.999999));const right=V().crossVectors(tangent,V(0,1,0));if(right.lengthSq()<.0001)right.set(0,0,1);right.normalize();const up=V().crossVectors(right,tangent).normalize();const a=curve.getTangentAt(clamp(t-.008,0,.9999)),b=curve.getTangentAt(clamp(t+.008,0,.9999));let bank=clamp((a.x*b.z-a.z*b.x)*4,-.5,.5);right.applyAxisAngle(tangent,bank);up.applyAxisAngle(tangent,bank);return{p,tangent,right,up,bank}}
function channelGeometry(curve,r,closed,water=false){const pos=[],uv=[],idx=[],N=300,M=closed?32:20;for(let i=0;i<=N;i++){const f=slideFrame(curve,i/N);for(let j=0;j<=M;j++){const theta=closed?(j/M*Math.PI*2-Math.PI):(j/M-.5)*(water?1.15:3.3);const p=f.p.clone().addScaledVector(f.right,Math.sin(theta)*r).addScaledVector(f.up,(1-Math.cos(theta))*r+(water?.035:0));pos.push(...p.toArray());uv.push(j/M,i*curve.getLength()/N*.35);if(i<N&&j<M){const k=i*(M+1)+j;idx.push(k,k+M+1,k+1,k+1,k+M+1,k+M+2)}}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g}
export class SlideSystem{
 constructor(scene,environment){this.scene=scene;this.environment=environment;this.rides=rideDefinitions.map(d=>({...d,curve:new THREE.CatmullRomCurve3(d.nodes.map(n=>V(...n)),false,'centripetal')}));this.flowMaterials=[];this.rings=[];for(const ride of this.rides){this.build(ride);ride.samples=Array.from({length:151},(_,i)=>slideFrame(ride.curve,i/150))}environment.additionalCollider=(x,z,y)=>this.blocked(x,z,y);environment.flush()}
 build(r){r.length=r.curve.getLength();r.launch=r.curve.getPointAt(0);r.exit=r.curve.getPointAt(1);const shell=new THREE.MeshPhysicalMaterial({color:r.color,roughness:.23,metalness:.05,clearcoat:.8,clearcoatRoughness:.14,side:THREE.DoubleSide});const g=channelGeometry(r.curve,r.radius,r.closed);const m=new THREE.Mesh(g,shell);m.castShadow=true;m.receiveShadow=true;this.scene.add(m);r.mesh=m;
 if(!r.closed){for(let side of [-1,1]){const pts=[];for(let i=0;i<=150;i++){const f=slideFrame(r.curve,i/150);pts.push(f.p.clone().addScaledVector(f.right,side*r.radius).addScaledVector(f.up,r.radius*1.085))}const edge=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),150,.065,7,false),mats.white);edge.castShadow=true;this.scene.add(edge)}}else{ // physical tunnel rings and emissive windows; double-sided shell is its true interior
 for(let t=.1;t<.97;t+=.09){const f=slideFrame(r.curve,t);const ring=new THREE.Mesh(new THREE.TorusGeometry(r.radius+.018,.018,6,32),new THREE.MeshBasicMaterial({color:t<.5?0x826aeb:0x46c4db}));ring.position.copy(f.p).addScaledVector(f.up,r.radius);ring.quaternion.setFromUnitVectors(V(0,0,1),f.tangent);this.scene.add(ring);this.rings.push(ring)}const dark=shell.clone();dark.color.set(0x1d152d);dark.emissive.set(0x161020);dark.emissiveIntensity=.15;m.material=dark;
 }
 const flow=new THREE.MeshStandardMaterial({color:0x8ce2db,transparent:true,opacity:.67,roughness:.16,metalness:.25,side:THREE.DoubleSide,depthWrite:false});flow.onBeforeCompile=shader=>{shader.uniforms.flowTime={value:0};flow.userData.shader=shader;shader.fragmentShader='uniform float flowTime;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nfloat streak=pow(.5+.5*sin(vMapUv.y*12.0-flowTime*14.0+sin(vMapUv.x*26.0)*1.2),12.0);diffuseColor.rgb+=streak*.20;')};flow.map=mats.tile.map;this.flowMaterials.push(flow);const water=new THREE.Mesh(channelGeometry(r.curve,r.radius,false,true),flow);water.renderOrder=1;this.scene.add(water);
 const n=Math.ceil(r.length/12);for(let i=1;i<n;i++){let f=slideFrame(r.curve,i/n);let p=f.p;if(p.y<1.1)continue;for(let s of [-1,1]){const top=p.clone().addScaledVector(f.right,s*(r.radius+.16)).addScaledVector(f.up,.35);this.environment.beam(V(top.x,0,top.z),top,.09,mats.teal)}this.environment.beam(p.clone().addScaledVector(f.right,-r.radius-.2),p.clone().addScaledVector(f.right,r.radius+.2),.10,mats.metal)}
 this.environment.mesh(new THREE.BoxGeometry(2.8,1,.12),sign(r.name,r.tag,'#'+r.color.toString(16).padStart(6,'0')),r.launch.x-1.8,r.launch.y+1.7,r.launch.z+1.8);if(r.drop){const capsule=new THREE.Mesh(new THREE.CylinderGeometry(.95,.95,2.8,28,1,true),new THREE.MeshPhysicalMaterial({color:0xbce0d8,transparent:true,opacity:.24,roughness:.12,side:THREE.DoubleSide}));capsule.position.copy(r.launch).add(V(0,1.5,0));this.scene.add(capsule)}
 }
 update(t){for(const m of this.flowMaterials)if(m.userData.shader)m.userData.shader.uniforms.flowTime.value=t}
 blocked(x,z,y){if(y>4)return false;for(const r of this.rides){if(x<Math.min(...r.nodes.map(n=>n[0]))-r.radius-2||x>Math.max(...r.nodes.map(n=>n[0]))+r.radius+2)continue;for(let i=0;i<r.samples.length;i++){const f=r.samples[i];if(f.p.y>y+3||Math.hypot(x-f.p.x,z-f.p.z)>r.radius+1.5)continue;const delta=V(x,y+.95,z).sub(f.p);const along=delta.dot(f.tangent);if(Math.abs(along)>.55||(i===150&&along>0))continue;const side=delta.dot(f.right),height=delta.dot(f.up),dist=Math.hypot(side,height-r.radius);if(Math.abs(dist-r.radius)<.32&&(r.closed||height<r.radius*1.12))return true}}return false}
 nearby(pos){return this.rides.find(r=>Math.abs(pos.y-r.launch.y)<.65&&Math.hypot(pos.x-r.launch.x,pos.z-r.launch.z)<2.7)}
}
export class Ride{
 constructor(config){this.config=config;this.distance=0;this.speed=2.2;this.phase=config.drop?'countdown':'channel';this.countdown=config.drop?3:0;this.p=config.launch.clone();this.velocity=V();this.time=0;this.airborneTime=0;this.splash=false;this.frame=slideFrame(config.curve,0)}
 update(dt){this.time+=dt;const r=this.config;if(this.phase==='countdown'){this.countdown-=dt;if(this.countdown<=0){this.phase='channel';this.speed=3}return}if(this.phase==='channel'){const t=clamp(this.distance/r.length,0,.999999);const f=slideFrame(r.curve,t);const slope=-f.tangent.y;const curvature=Math.abs(f.bank);this.speed=clamp(this.speed+(9.81*slope+.8-r.friction*this.speed-curvature*this.speed*.3)*dt,2.3,r.maxSpeed);this.distance=Math.min(r.length,this.distance+this.speed*dt);this.frame=slideFrame(r.curve,this.distance/r.length);this.p.copy(this.frame.p).addScaledVector(this.frame.up,r.tube?.26:.10);if(this.distance>=r.length){if(r.jump){this.phase='flight';// Ramp lip transfers approach momentum upward; controlled fantasy launch keeps the trajectory inside its dedicated pool.
 this.velocity.copy(this.frame.tangent).multiplyScalar(Math.min(this.speed,10.8));this.velocity.y=Math.max(this.velocity.y,7.2);this.p.copy(r.exit).add(V(0,.35,0));}else{this.phase='splash';this.velocity.copy(this.frame.tangent).multiplyScalar(this.speed*.27);this.velocity.y=-3;}}return}if(this.phase==='flight'){this.airborneTime+=dt;this.velocity.y-=9.81*dt;this.p.addScaledVector(this.velocity,dt);this.frame.tangent.copy(this.velocity).normalize();if(this.p.y<.05){this.phase='splash';this.splash=true;this.velocity.multiplyScalar(.17);this.velocity.y=-4.5}return}if(this.phase==='splash'){this.splash=true;this.velocity.y+=dt*5.8;this.velocity.x*=Math.exp(-dt*3);this.velocity.z*=Math.exp(-dt*3);this.p.addScaledVector(this.velocity,dt);if(this.p.y<-.9){this.p.y=-.9;this.velocity.y=Math.max(0,this.velocity.y)}if(this.velocity.y>0&&this.p.y>-.15){this.phase='done';this.p.y=-.65}}
 }
}
export function makeTube(){const g=new THREE.Group();const m=new THREE.MeshPhysicalMaterial({color:0xf2cf62,roughness:.34,clearcoat:.5});const ring=new THREE.Mesh(new THREE.TorusGeometry(.72,.23,16,48),m);ring.rotation.x=Math.PI/2;ring.castShadow=true;g.add(ring);for(let s of [-1,1]){const handle=new THREE.Mesh(new THREE.TorusGeometry(.12,.028,6,12,Math.PI),mats.dark);handle.position.set(s*.7,.15,.1);handle.rotation.y=Math.PI/2;g.add(handle)}return g}
