import {V,range,rand,poolAt,waveHeight} from './config.js';
import {Ride,makeTube} from './slides.js';
const routes=[[[8,36],[-6,24],[-35,18],[-43,-14],[-50,-20],[-50,-29]],[[8,36],[19,29],[21,44],[36,48],[48,23],[42,11]],[[8,36],[-6,24],[-35,18],[-39,40],[-6,47],[8,36]]];
export class Visitors{
 constructor(factory,scene,env,slides,water,mobile){this.factory=factory;this.env=env;this.slides=slides;this.water=water;this.scene=scene;this.people=[];this.count=mobile?24:44;for(let i=0;i<this.count;i++){const model=factory.create(i%12);scene.add(model);const person={model,index:i,state:'walk',phase:rand()*30,wait:range(8,30),route:i%3,waypoint:0,speed:range(.7,1.3),ride:null,tube:null};if(i<9){person.state=i<5?'swim':'wade';person.anchor=V(3+range(-6,15),0,i<5?range(-13,2):range(14,18));model.position.copy(person.anchor)}else if(i<13){person.state='talk';model.position.set(-8+(i%2)*1.5,0,22+Math.floor(i/2)%2*1.6);model.rotation.y=i%2?2.8:.1}else if(i<18){person.state='sit';model.position.set([-2.4,6.6,17.6,40.6,29.6][i-13],-.50,[28.45,31.45,31.45,46.45,48.45][i-13]);model.rotation.y=Math.PI}else if(i<22){person.state=i%2?'watch':'wade';model.position.set(-23+(i%4)*2.8,i%2?0:-.2,34);person.anchor=model.position.clone()}else{const route=routes[i%3];person.waypoint=i%route.length;let p=route[person.waypoint],prev=route[(person.waypoint+route.length-1)%route.length],alpha=rand();model.position.set(prev[0]+(p[0]-prev[0])*alpha+range(-.4,.4),0,prev[1]+(p[1]-prev[1])*alpha);}this.people.push(person)}
 // A visitor starts on the tower, then uses the complete ride / splash / exit state cycle.
 this.riderStart=mobile?19:22;for(let i=this.riderStart;i<this.riderStart+5;i++){const p=this.people[i];p.state='climb';p.stairIndex=(i-this.riderStart)*5;p.model.position.copy(env.stairRoute[p.stairIndex]);p.rideIndex=(i-this.riderStart)%5}
 }
 moveTo(p,target,dt){const d=target.clone().sub(p.model.position);const len=Math.hypot(d.x,d.z,d.y);if(len<.12){p.model.position.copy(target);return true}const step=Math.min(len,p.speed*dt),next=p.model.position.clone().addScaledVector(d,step/len);if(p.state==='climb'||!this.env.blocked(next.x,next.z,next.y)){p.model.position.copy(next)}else{p.wait-=dt;if(p.wait<0){p.waypoint=(p.waypoint+1)%routes[p.route].length;p.wait=10}}p.model.rotation.y=Math.atan2(d.x,d.z);return false}
 update(dt,t){for(const p of this.people){const model=p.model;if(p.state==='swim'||p.state==='wade'){const x=p.anchor.x+Math.sin(t*.13+p.phase)*.7,z=p.anchor.z+Math.cos(t*.1+p.phase)*.7;model.position.x=x;model.position.z=z;model.position.y=p.state==='swim'?waveHeight(x,z,t,this.water.on)-.85:this.env.floor(x,z,0);model.rotation.y=Math.sin(t*.18+p.phase);if(p.state==='swim'&&rand()<dt*.2)this.water.splash(x,z,.45)}else if(p.state==='walk'){const route=routes[p.route],q=route[p.waypoint],target=V(q[0],0,q[1]);if(this.moveTo(p,target,dt)){p.waypoint=(p.waypoint+1)%route.length;if(p.route===0&&p.waypoint===0&&p.index>=this.riderStart){p.state='climb';p.stairIndex=0;p.rideIndex=p.rideIndex===undefined?p.index%5:(p.rideIndex+1)%5;p.model.position.copy(this.env.stairRoute[0])}}model.position.y=this.env.floor(model.position.x,model.position.z,model.position.y)}else if(p.state==='climb'){const r=this.slides.rides[p.rideIndex],route=this.env.accessRoute(r),final=route.length-1;const target=route[Math.min(p.stairIndex,final)];if(this.moveTo(p,target,dt)){p.stairIndex++;if(p.stairIndex>final){p.state='queue';p.wait=range(2,6)}}}else if(p.state==='queue'){const r=this.slides.rides[p.rideIndex];if(this.moveTo(p,r.launch,dt)){p.wait-=dt;if(p.wait<=0&&t-(r.lastLaunch||-10)>4){r.lastLaunch=t;p.state='ride';p.ride=new Ride(r);if(r.tube){p.tube=makeTube();this.scene.add(p.tube)}}}}else if(p.state==='ride'){p.ride.update(dt);model.position.copy(p.ride.p).add(V(0,-.55,0));const f=p.ride.frame;model.rotation.y=Math.atan2(f.tangent.x,f.tangent.z);if(p.tube){p.tube.position.copy(p.ride.p);p.tube.rotation.y=t*.8;p.tube.rotation.z=f.bank}if(p.ride.splash&&!p.didSplash){this.water.splash(model.position.x,model.position.z,1.4);p.didSplash=true}if(p.ride.phase==='done'){p.state='exit';p.wait=0;p.ride=null;p.didSplash=false;}}else if(p.state==='exit'){const pool=poolAt(model.position.x,model.position.z);const target=pool?V(pool.x,-.6,pool.z+pool.rz+1):V(-34,0,16);this.moveTo(p,target,dt);if(!pool){p.state='walk';p.route=0;p.waypoint=0;model.position.y=0;if(p.tube){this.scene.remove(p.tube);p.tube.traverse(o=>{if(o.isMesh){o.geometry.dispose()}});p.tube=null}}else model.position.y=waveHeight(model.position.x,model.position.z,t,this.water.on)-.65;if(p.tube)p.tube.position.copy(model.position).add(V(0,.7,0));}
 // Animation update reduced to 15–30 Hz; root motion and waves remain continuous.
 p.animTime=(p.animTime||0)+dt;if(p.animTime>1/24){this.factory.animate(model,p.state==='exit'?'swim':p.state,p.phase+t,p.speed);p.animTime=0}}
 for(let i=0;i<this.people.length;i++)for(let j=i+1;j<this.people.length;j++){const a=this.people[i],b=this.people[j];if(a.state!=='walk'||b.state!=='walk')continue;const dx=a.model.position.x-b.model.position.x,dz=a.model.position.z-b.model.position.z,l=Math.hypot(dx,dz);if(l<.75&&l>.005){const push=(.75-l)*.08;const x=a.model.position.x+dx/l*push,z=a.model.position.z+dz/l*push;if(!this.env.blocked(x,z,a.model.position.y)){a.model.position.x=x;a.model.position.z=z}}}
 }
}
