import * as THREE from 'three';
import {Reflector} from 'three/addons/objects/Reflector.js';
import {pools,V,poolBottom,rand,range} from './config.js';
const vertex=`uniform float time;uniform float amplitude;uniform vec3 pool;uniform vec2 bounds;uniform mat4 textureMatrix;varying vec3 world;varying vec4 mirror;varying float depth;varying vec2 vUv;
void main(){vec3 p=position;vUv=uv;vec4 w=modelMatrix*vec4(p,1.);float shore=pool.z+bounds.y*sqrt(max(0.,1.-pow((w.x-pool.x)/bounds.x,2.)));depth=pool.y>0.5?clamp((shore-w.z)*.14-.05,0.,3.2):1.7;float wave=min(depth*.24,.38)*amplitude*sin(w.z*.48-time*1.65);w.y+=wave+.025*sin(w.x*1.9-w.z*1.1+time*2.);world=w.xyz;mirror=textureMatrix*vec4(position,1.);gl_Position=projectionMatrix*viewMatrix*w;}`;
const fragment=`precision highp float;uniform float time;uniform float amplitude;uniform sampler2D tDiffuse;uniform float reflected;uniform vec3 pool;uniform vec2 bounds;uniform vec3 sun;varying vec3 world;varying vec4 mirror;varying float depth;varying vec2 vUv;
float rip(vec2 p){return sin(p.x*2.3+p.y*1.1+time*1.7)*.45+sin(p.y*3.8-p.x*.9-time*1.4)*.25+sin(p.x*8.1+p.y*7.3+time*2.5)*.07;}
void main(){vec2 p=world.xz;float a=rip(p),b=rip(p+vec2(.07,0)),c=rip(p+vec2(0,.07));vec3 n=normalize(vec3((a-b)*1.8,1.,(a-c)*1.8-amplitude*.13*cos(world.z*.48-time*1.65)));vec3 v=normalize(cameraPosition-world);float fres=.06+.48*pow(1.-max(dot(n,v),0.),4.);vec3 shallow=vec3(.36,.79,.70),deep=vec3(.025,.37,.42);vec3 base=mix(shallow,deep,smoothstep(0.,3.3,depth));vec2 coord=mirror.xy/mirror.w+n.xz*.018;vec3 reflection=mix(vec3(.63,.83,.85),texture2D(tDiffuse,coord).rgb*vec3(.78,.94,.91),reflected);vec3 color=mix(base,reflection,fres);float spec=pow(max(dot(reflect(-normalize(sun),n),v),0.),200.);color+=vec3(1.,.97,.82)*spec*2.1;float crest=smoothstep(.89,1.,sin(world.z*.48-time*1.65))*amplitude*smoothstep(.05,.25,depth)*(1.-smoothstep(.3,1.0,depth));float edge=(1.-smoothstep(.015,.18,depth))*(.5+.5*sin(world.x*6.+world.z*4.+time*3.));color=mix(color,vec3(.92,.99,.93),clamp(crest+edge,0.,.8));float alpha=mix(.32,.91,smoothstep(0.,1.7,depth));gl_FragColor=vec4(color,alpha);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`;
export class WaterSystem{
 constructor(scene,mobile){this.scene=scene;this.time=0;this.on=true;this.jets=true;this.objects=[];this.splashes=[];this.mobile=mobile;const plane=new THREE.PlaneGeometry(120,120);this.reflector=new Reflector(plane,{textureWidth:mobile?256:512,textureHeight:mobile?256:512,multisample:0});this.reflector.rotation.x=-Math.PI/2;this.reflector.position.y=.02;this.reflector.material.colorWrite=false;this.reflector.material.depthWrite=false;this.reflector.renderOrder=-2;scene.add(this.reflector);const reflectionUniforms=this.reflector.material.uniforms;this.reflectionMatrix={value:new THREE.Matrix4()};
 for(const p of pools){const g=new THREE.CircleGeometry(1,100); // subdivided radial rings for physical wave displacement
 const pos=[],uv=[],idx=[],rings=52,segments=96;for(let i=0;i<=rings;i++){const r=i/rings;for(let j=0;j<=segments;j++){const a=j/segments*6.283185;pos.push(p.x+Math.cos(a)*p.rx*r,.03,p.z+Math.sin(a)*p.rz*r);uv.push((Math.cos(a)*r+1)/2,(Math.sin(a)*r+1)/2);if(i<rings&&j<segments){const k=i*(segments+1)+j;idx.push(k,k+1,k+segments+1,k+1,k+segments+2,k+segments+1)}}}g.dispose();const geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geom.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geom.setIndex(idx);const m=new THREE.ShaderMaterial({uniforms:{time:{value:0},amplitude:{value:p.beach?1:.035},pool:{value:V(p.x,p.beach?1:0,p.z)},bounds:{value:new THREE.Vector2(p.rx,p.rz)},sun:{value:V(-.5,.8,.4)},tDiffuse:reflectionUniforms.tDiffuse,textureMatrix:this.reflectionMatrix,reflected:{value:1}},vertexShader:vertex,fragmentShader:fragment,transparent:true,side:THREE.DoubleSide,depthWrite:false});const mesh=new THREE.Mesh(geom,m);mesh.renderOrder=2;scene.add(mesh);this.objects.push(mesh)}
 // lightweight animated point spray: splash playground + waterfall under wave machine
 const count=650,pts=[],params=[];for(let i=0;i<count;i++){const fountain=i<350;params.push({fountain,origin:V(fountain?(-28+(i%3)*9):12+range(-9,9),fountain?1.2:1.5,fountain?30:-23),phase:rand(),angle:rand()*6.28,speed:range(1,2)});pts.push(0,0,0)}const geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));this.spray=new THREE.Points(geom,new THREE.PointsMaterial({color:0xe2ffff,size:.10,transparent:true,opacity:.65,depthWrite:false}));this.spray.renderOrder=3;scene.add(this.spray);this.params=params;
 const ringGeometry=new THREE.RingGeometry(.75,1,36);ringGeometry.rotateX(-Math.PI/2);for(let i=0;i<18;i++){const ring=new THREE.Mesh(ringGeometry,new THREE.MeshBasicMaterial({color:0xd8ffed,transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide}));ring.visible=false;scene.add(ring);this.splashes.push({ring,life:0})}
 const original=this.reflector.onBeforeRender;let frame=0;this.reflector.onBeforeRender=(renderer,scene,camera)=>{if(++frame%(this.mobile?4:2)!==0||camera.position.y<.1)return;this.objects.forEach(m=>m.visible=false);original.call(this.reflector,renderer,scene,camera);this.reflectionMatrix.value.copy(reflectionUniforms.textureMatrix.value).multiply(this.reflector.matrixWorld.clone().invert());this.objects.forEach(m=>m.visible=true)};
 }
 splash(x,z,strength=1){const s=this.splashes.find(s=>s.life<=0)||this.splashes[0];s.life=1.4;s.strength=strength;s.ring.position.set(x,.08,z);s.ring.scale.setScalar(.4);s.ring.visible=true}
 update(t,dt){this.time=t;for(const m of this.objects){m.material.uniforms.time.value=t;m.material.uniforms.amplitude.value=m.material.uniforms.pool.value.y>.5?(this.on?.65+.35*Math.sin(t*.07)**2:.12):.035}const a=this.spray.geometry.attributes.position;this.params.forEach((p,i)=>{const age=(t*p.speed*.35+p.phase)%1;const life=age*1.8;let x=p.origin.x,z=p.origin.z,y;if(p.fountain){x+=Math.cos(p.angle)*life*.9;z+=Math.sin(p.angle)*life*.9;y=p.origin.y+life*3-life*life*2.1}else{z+=life*1.5;y=p.origin.y-life*life*2.2}a.setXYZ(i,x,p.fountain&&!this.jets?-30:Math.max(.03,y),z)});a.needsUpdate=true;for(const s of this.splashes)if(s.life>0){s.life-=dt;const age=1.4-s.life;s.ring.scale.setScalar((.5+age*2.6)*s.strength);s.ring.material.opacity=Math.max(0,s.life*.3);if(s.life<=0)s.ring.visible=false}}
}
